const statusCode = {
  SUCCESS: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NOT_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOW: 405,
  NOT_ACCEPTABLE: 406,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};
const constants = {
  SUCCESS: "SUCCESS",
  CREATED: "NEW DOCUMENT CREATED SUCCESS",
  UNAUTHORIZED: "YOU ARE UNAUTHORIZED USERS",
  BAD_REQUEST: "BAD REQUEST ",
  FORBIDDEN: "YOU ARE NOT ALLOW TO ACCESS ",
  NOT_FOUND: "DOCUMENT NOT FOUND ",
  USER_NOT_FOUND:"user not found",
  LOGIN_SUCCESS:"Login successs ",
  CONFLICT: "ALREADY EXISTS DOCUMENT",
  INTERNAL_SERVER_ERROR: "INTERNAL SERVER ERROR",
  FOUND: "DOCUMENT FOUND ",
  MISSING_FIELD:"FIELD IS MISSING"
};
module.exports = { statusCode, constants };
